# Generated by Django 5.1.1 on 2024-09-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('jenis_transaksi', models.CharField(choices=[('P', 'Pengeluaran'), ('M', 'Pemasukan')], max_length=1)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keterangan', models.TextField()),
                ('bukti', models.FileField(upload_to='bukti_transaksi/')),
            ],
        ),
    ]
