# Generated by Django 5.1.1 on 2024-09-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='anggota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
