# Generated by Django 5.1.1 on 2024-09-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_transaksi_anggota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='anggota',
            field=models.CharField(blank=True, choices=[('Uti Nur Padila', 'Uti Nur Padila'), ('Nur Aini', 'Nur Aini')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='bukti',
            field=models.FileField(blank=True, null=True, upload_to='bukti_transaksi/'),
        ),
    ]
