# Generated by Django 5.1.1 on 2024-09-13 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0005_alter_transaksi_anggota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='anggota',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='transaksi.anggota'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='jumlah',
            field=models.IntegerField(),
        ),
    ]
