# Generated by Django 5.1.1 on 2024-09-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0006_alter_transaksi_anggota_alter_transaksi_jumlah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='tanggal',
            field=models.DateField(blank=True),
        ),
    ]
